# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5c272f999fe5b544fa2a8004c774a162f2eb2d1ae3c41d9a242b9a58ff1103e66a80412c7d4baa9e0180fd91621cdb6462c08dd13db89826a14d623788de6d9

test:
  secret_key_base: 66d46079156aad8285ea8f074bec0735c1236e65d730047a08b534bf04c1a4a7d3a64d5ac0af818c6a9332c0f30fbed2f5ae713134f775843aaf02b4ebad33ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
